runtime: nodejs14
entrypoint: node back/app.js
handlers:
  - url: /
    static_files: front/build/index.html
    upload: front/build/index.html

  - url: /(.*\.(json|ico|js|css|txt))$
    static_files: front/build/\1
    upload: front/build/.*\.(json|ico|js|css|txt)$

  - url: /api/.*
    script: auto

  - url: /.*
    static_files: front/build/index.html
    upload: front/build/index.html
