steps:
  - name: 'node'
    entrypoint: npm
    args: ['install']
    dir: front
  - name: 'node'
    entrypoint: npm
    args: ['run', 'build']
    dir: front
  - name: 'node'
    entrypoint: npm
    args: ['install']
    dir: back
