runtime: nodejs14
entrypoint: node app.js
handlers:
  - url: /api/.*
    script: auto

  - url: /(.*\..+)$
    static_files: front/\1
    upload: front/(.*\..+)$
  - url: .*
    static_files: front/index.html
    upload: front/index.html
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
