name: GAE deploy
on: [push]
jobs:
  back-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Save the api key
        run: 'echo "$SECRET_FILE" > api_key.json'
        shell: bash
        env:
          SECRET_FILE: ${{ secrets.API_KEY_FOR_BACK }}
        working-directory: ./back
      - name: Save the sa key
        run: 'echo "$SECRET_FILE" > credential.json'
        shell: bash
        env:
          SECRET_FILE: ${{ secrets.SA_KEY_FOR_BACK }}
        working-directory: ./back
      - run: npm ci
        working-directory: ./back

  fron-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: mkdir environment
        run: mkdir src/environments
        working-directory: ./front
      - name: Save the environment
        run: 'echo "$SECRET_FILE" > src/environments/environment.prod.ts'
        shell: bash
        env:
          SECRET_FILE: ${{ secrets.ENV_FOR_FRONT }}
        working-directory: ./front
      - name: Save the environment
        run: 'echo "$SECRET_FILE" > src/environments/environment.ts'
        shell: bash
        env:
          SECRET_FILE: ${{ secrets.ENV_FOR_FRONT }}
        working-directory: ./front
      - run: npm ci
        working-directory: ./front
      - run: npm run build
        working-directory: ./front

  deplay-staging:
    name: GAE deplay
    needs: [fron-build, back-build]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0.3.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}
          version: v1
