name: GAE deploy
on: [push]
jobs:
  back-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Back
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Save the api key
        run: echo env.SECRET_FILE > api_key.json
        env:
          SECRET_FILE: ${{ secrets.API_KEY_FOR_BACK }}
      - name: Save the sa key
        run: echo env.SECRET_FILE > credential.json
        env:
          SECRET_FILE: ${{ secrets.SA_KEY_FOR_BACK }}
      - run: npm ci
        working-directory: ./back

  fron-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Prepare front
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Save the environment
        run: echo env.SECRET_FILE > src/environments/environment.prod.ts
        env:
          SECRET_FILE: ${{ secrets.ENV_FOR_FRONT }}
        working-directory: ./front
      - run: npm ci
        working-directory: ./front
      - run: npm run build
        working-directory: ./front

  deplay-staging:
    name: GAE deplay
    needs: [fron-build, back-build]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0.3.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}
          version: v1
